CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "NombreCompleto" text NOT NULL,
    "Telefono" text NOT NULL,
    "FechaRegistro" timestamp with time zone NOT NULL,
    "SocioId" uuid,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Clases" (
    "Id" uuid NOT NULL,
    "Nombre" text NOT NULL,
    "Descripcion" text NOT NULL,
    "DuracionMinutos" integer NOT NULL,
    CONSTRAINT "PK_Clases" PRIMARY KEY ("Id")
);

CREATE TABLE "Socios" (
    "Id" uuid NOT NULL,
    "Nombre" text NOT NULL,
    "Email" text NOT NULL,
    "Telefono" text NOT NULL,
    "FechaRegistro" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Socios" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "HorariosClases" (
    "Id" uuid NOT NULL,
    "ClaseId" uuid NOT NULL,
    "Instructor" text NOT NULL,
    "FechaHoraInicio" timestamp with time zone NOT NULL,
    "CupoMaximo" integer NOT NULL,
    CONSTRAINT "PK_HorariosClases" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HorariosClases_Clases_ClaseId" FOREIGN KEY ("ClaseId") REFERENCES "Clases" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Membresias" (
    "Id" uuid NOT NULL,
    "SocioId" uuid NOT NULL,
    "TipoPlan" text NOT NULL,
    "FechaInicio" timestamp with time zone NOT NULL,
    "FechaFin" timestamp with time zone NOT NULL,
    "Estado" integer NOT NULL,
    CONSTRAINT "PK_Membresias" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Membresias_Socios_SocioId" FOREIGN KEY ("SocioId") REFERENCES "Socios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Reservas" (
    "Id" uuid NOT NULL,
    "HorarioClaseId" uuid NOT NULL,
    "SocioId" uuid NOT NULL,
    "Estado" integer NOT NULL,
    "PosicionListaEspera" integer,
    "FechaRegistro" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Reservas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reservas_HorariosClases_HorarioClaseId" FOREIGN KEY ("HorarioClaseId") REFERENCES "HorariosClases" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Reservas_Socios_SocioId" FOREIGN KEY ("SocioId") REFERENCES "Socios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Asistencias" (
    "Id" uuid NOT NULL,
    "ReservaId" uuid NOT NULL,
    "FechaIngreso" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Asistencias" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Asistencias_Reservas_ReservaId" FOREIGN KEY ("ReservaId") REFERENCES "Reservas" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Asistencias_ReservaId" ON "Asistencias" ("ReservaId");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_HorariosClases_ClaseId" ON "HorariosClases" ("ClaseId");

CREATE INDEX "IX_Membresias_SocioId" ON "Membresias" ("SocioId");

CREATE INDEX "IX_Reservas_HorarioClaseId" ON "Reservas" ("HorarioClaseId");

CREATE INDEX "IX_Reservas_SocioId" ON "Reservas" ("SocioId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260919203041_InitialCreate', '8.0.11');

COMMIT;

